Python 2.6:
  script:
  - py_version=2.6
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/build-and-test-py-project.sh
  - export REQUIREMENTS_TXT=requirements.dev.txt
  - ". ./build-and-test-py-project.sh"
  tags:
  - python2.6
  - linux
  except:
  - tags
  artifacts:
    reports:
      junit: test/pytest.xml

Python 2.6:
  script:
  - py_version=2.6
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/build-and-test-py-project.sh
  - export REQUIREMENTS_TXT=requirements.dev-2.6.txt
  - ". ./build-and-test-py-project.sh"
  tags:
  - python2.6
  - linux
  except:
  - tags
  artifacts:
    reports:
      junit: test/pytest.xml

Python 2.7:
  script:
  - py_version=2.7
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/build-and-test-py-project.sh
  - export REQUIREMENTS_TXT=requirements.dev.txt
  - ". ./build-and-test-py-project.sh"
  tags:
  - python2.7
  - linux
  except:
  - tags
  artifacts:
    reports:
      junit: test/pytest.xml

Python 3.5:
  script:
  - py_version=3.5
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/build-and-test-py-project.sh
  - export REQUIREMENTS_TXT=requirements.dev.txt
  - ". ./build-and-test-py-project.sh"
  tags:
  - python3.5
  - linux
  except:
  - tags
  artifacts:
    reports:
      junit: test/pytest.xml

Python 3.6:
  script:
  - py_version=3.6
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/build-and-test-py-project.sh
  - export REQUIREMENTS_TXT=requirements.dev.txt
  - ". ./build-and-test-py-project.sh"
  tags:
  - python3.6
  - linux
  except:
  - tags
  artifacts:
    reports:
      junit: test/pytest.xml

Python 3.7:
  script:
  - py_version=3.7
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/build-and-test-py-project.sh
  - export REQUIREMENTS_TXT=requirements.dev.txt
  - ". ./build-and-test-py-project.sh"
  tags:
  - python3.7
  - linux
  except:
  - tags
  artifacts:
    reports:
      junit: test/pytest.xml

Flake8:
  script:
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/prepare-and-run-flake8.sh
  - ". ./prepare-and-run-flake8.sh pudb test"
  tags:
  - python3.5
  except:
  - tags

Documentation:
  script:
  - EXTRA_INSTALL="numpy mako"
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/build-docs.sh
  - ". ./build-docs.sh"
  tags:
  - python3.5
  only:
  - master
