language: python
python:
  - "2.6"
  - "2.7"
  - "3.5"
  - "3.6"

# command to install dependencies
install:
    - |
        PY_VER=$(python -c 'import sys; sys.stdout.write("%d.%d" % sys.version_info[:2])') ; \
        if test "$PY_VER" = "2.6"; then \
            pip install -r requirements.dev-2.6.txt; \
        else \
            pip install -r requirements.dev.txt; \
        fi
    - "pip install -e ."

# command to run tests
script:
    - "(cd test && pytest --cov=pudb)"

after_success:
  - bash upload_coverage.sh

sudo: false
